# Generated by Django 4.2.7 on 2023-12-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.TextField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.TextField(max_length=100)),
                ("des", models.TextField(max_length=100)),
            ],
        ),
    ]
